from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]

PAGES = [
    dict(id="number-one-auto", business="Number One Auto", initials="N1", vertical="auto repair", market="Iowa City", phone="(319) 354-3932", tel="13193543932", issue="public site certificate warning", headline="Turn a scary browser warning into a trusted repair call.", lede="A premium mobile-first concept for Number One Auto that rebuilds confidence fast: the issue is clear, the call button is close, and Iowa City drivers get a real repair path instead of a warning screen.", accent="#f97316", accent2="#38bdf8", bg="#070b13", lat=41.6611, lon=-91.5302, section="certificate rescue", routes=[("Repair call", "Fast path for drivers who need a mechanic and do not want to fight a broken site."),("Diagnostics", "Simple lane for noises, warning lights, inspections, and unknown issues."),("Trust rebuild", "Explain that the site is being modernized without over-claiming certifications or reviews."),("After-hours", "Capture mobile visitors who find the shop after business hours.")], services=[("General repair", "A clean, confidence-first path for common repair inquiries."),("Diagnostics", "Explain inspection/diagnostic requests without inventing a menu."),("Mobile call path", "Tap-to-call remains visible before the customer bounces."),("Website recovery", "Replace the broken first impression with a safe, modern landing page.")], proof=[("Verified issue", "Earlier pass found the public site failing with an expired-certificate warning."),("Public details only", "Uses business name, Iowa City market, and public phone."),("Send-safe framing", "Positions this as a helpful concept, not an attack on the current site.")]),
    dict(id="sd-auto-repair-center", business="S & D Auto Repair Center", initials="S&D", vertical="auto repair", market="Iowa City", phone="(319) 569-2176", tel="13195692176", issue="public route landed on Google sign-in", headline="Make the first click open a repair page, not a login screen.", lede="A call-first concept for S & D Auto Repair Center: built around the public-path issue, with a cleaner service route for Iowa City drivers on mobile.", accent="#22c55e", accent2="#f59e0b", bg="#07110c", lat=41.6611, lon=-91.5302, section="login-wall fix", routes=[("Need repair", "Move visitors straight from search to a phone-first repair path."),("Vehicle concern", "Give customers a simple way to describe a problem before calling."),("Location check", "Ground the page in Iowa City instead of sending people to a blocked route."),("Quote question", "A short message path for non-urgent work once approved.")], services=[("Repair requests", "Plain-language repair path without unsupported claims."),("Inspection needs", "A safe lane for unknown vehicle problems."),("Phone-first UX", "Keeps the call action visible on small screens."),("Public page fix", "Replaces a confusing login-wall experience with a real landing page.")], proof=[("Verified issue", "Earlier pass found the website route landing on a Google sign-in screen."),("Local context", "Iowa City market and public phone anchor the concept."),("No fake badges", "No invented reviews, certifications, or warranty claims.")]),
    dict(id="eastern-iowa-spray-foam-waterproofing", business="Eastern Iowa Spray Foam & Waterproofing LLC", initials="EI", vertical="waterproofing / spray foam", market="Cedar Rapids / Waterloo corridor", phone="(319) 447-7480", tel="13194477480", issue="older mobile experience", headline="Give basement-water leads a faster estimate path.", lede="A premium waterproofing concept that turns an older brochure-style experience into a mobile estimate funnel for sump pumps, basement water, spray foam, and urgent questions.", accent="#14b8a6", accent2="#a3e635", bg="#061214", lat=42.0083, lon=-91.6441, section="waterproofing funnel", routes=[("Wet basement", "Lead with urgency and phone confidence for water problems."),("Spray foam", "Separate insulation inquiries from emergency-style waterproofing calls."),("Sump pump", "Make a common high-intent service easy to find."),("Estimate", "Create a clean quote path without forcing a long form.")], services=[("Basement waterproofing", "Clear path for water intrusion and foundation concerns."),("Sump pump help", "Easy next step for pump questions and replacements."),("Spray foam", "Dedicated lane for insulation/project inquiries."),("Mobile estimates", "Contact section designed around short, fast submissions.")], proof=[("Modernization angle", "Current site is functional but can be clearer on mobile."),("Service-specific", "Copy focuses on basement water, sump pumps, and spray foam."),("Production-ready", "Leaves room for real photos, licenses, reviews, and approved proof.")]),
    dict(id="quality-plumbing-marion", business="Quality Plumbing", initials="QP", vertical="plumbing", market="Marion / Cedar Rapids", phone="(319) 373-4114", tel="13193734114", issue="listed domain redirected to unrelated article", headline="Replace the wrong destination with a real plumbing call path.", lede="A premium emergency-plumbing concept for Quality Plumbing: built to turn a broken/unrelated public website path into a clean mobile call experience.", accent="#0ea5e9", accent2="#facc15", bg="#06101c", lat=42.0333, lon=-91.5969, section="wrong-route fix", routes=[("Emergency call", "Put burst-pipe and urgent plumbing callers one tap from the phone."),("Repair need", "Simple lane for leaks, drains, fixtures, and repair questions."),("Service area", "Anchor the page in Marion / Cedar Rapids instead of an unrelated destination."),("Estimate", "Short form path for non-emergency work.")], services=[("Emergency plumbing", "Mobile-first urgent call lane."),("Leaks & repairs", "Plain service grouping without over-claiming."),("Drain / fixture help", "Clear common-request routing."),("Website path repair", "Fix the mismatch between search click and business page.")], proof=[("Verified issue", "Earlier pass found the listed domain redirecting to an unrelated LocalHero plumbing article."),("Call-first", "Uses public phone and local market context."),("Respectful pitch", "Frames the fix as a helpful public-path cleanup.")]),
    dict(id="maxios-auto-repair", business="Maxio's Auto Repair", initials="MX", vertical="auto repair", market="Des Moines", phone="+1 515-528-2450", tel="15155282450", issue="Google Business Site URL returned 404", headline="A dead listing click should become a repair call.", lede="A premium concept for Maxio's Auto Repair that replaces a 404 business-site path with a fast Des Moines service page: phone, repair lanes, map, and simple contact.", accent="#ef4444", accent2="#60a5fa", bg="#120708", lat=41.5868, lon=-93.6250, section="404 recovery", routes=[("Call the shop", "Move high-intent visitors from a dead page to the phone."),("Repair / diagnostic", "Give a direct lane for common auto repair needs."),("Location", "Make Des Moines context visible immediately."),("Message", "Let non-urgent customers send a short question.")], services=[("Auto repair", "A safe, broad service lane without inventing specialties."),("Diagnostics", "Route unknown problems into a practical next step."),("Mobile trust", "Replace a broken business-site link with a polished first impression."),("Local conversion", "Map + phone + contact built for small screens.")], proof=[("Verified issue", "Earlier pass found the listed Google Business Site URL returning 404."),("High-intent category", "Auto repair clicks are urgent and phone-driven."),("No fake proof", "No fabricated ASE badges, reviews, coupons, or owner claims.")]),
    dict(id="howards-auto-repair", business="Howard's Auto Repair", initials="HA", vertical="auto repair", market="Oskaloosa", phone="+1-641-673-3310", tel="16416733310", issue="third-party Arnold Motor Supply URL returned 404", headline="Fix the 404 before Oskaloosa drivers choose another shop.", lede="A premium repair-page concept for Howard's Auto Repair that turns a third-party 404 into a call-first local service page with a warmer, more trustworthy first screen.", accent="#f59e0b", accent2="#93c5fd", bg="#11100a", lat=41.2964, lon=-92.6444, section="repair-ticket rescue", routes=[("Call now", "Give drivers a clear phone path from the first screen."),("Repair need", "Create a lane for common repair conversations without unsupported claims."),("Find us", "Ground the concept in Oskaloosa and the public listing context."),("Ask a question", "Non-urgent message path for production once approved.")], services=[("Repair calls", "Fast phone action for high-intent visitors."),("Diagnostics", "Simple route for unknown vehicle problems."),("Local presence", "A page that belongs to the shop, not a broken third-party path."),("Contact cleanup", "Make phone and map easier to use from mobile.")], proof=[("Verified issue", "Earlier pass found a third-party Arnold Motor Supply location URL returning 404."),("Public facts", "Uses public phone and Oskaloosa market only."),("Distinct design", "Warmer repair-ticket aesthetic, not a generic mechanic template.")]),
    dict(id="xpress-oil-lube-waterloo", business="Xpress Oil & Lube", initials="XO", vertical="oil & lube / auto service", market="Waterloo", phone="+1-319-232-0854", tel="13192320854", issue="listed domain failed DNS resolution", headline="When the domain is dead, the phone path has to be instant.", lede="A premium fast-lube landing concept for Xpress Oil & Lube: hours, phone, map, service lanes, and a bay-status feel built for Waterloo drivers on mobile.", accent="#f97316", accent2="#fde047", bg="#100b06", lat=42.4928, lon=-92.3426, section="dead-domain recovery", routes=[("Oil change", "Make the fastest service need obvious from the first screen."),("Service question", "Give customers a short path for other auto-service requests."),("Hours / location", "Keep Waterloo, hours context, and phone close."),("Call first", "Prioritize the action most likely to save a lost listing click.")], services=[("Oil & lube", "Fast-lane service framing without inventing coupons."),("Auto service", "Secondary path for general service questions."),("Hours visible", "Public hours can be confirmed and added in production."),("Domain fix", "Replace a dead domain with a stable, local landing page.")], proof=[("Verified issue", "Earlier pass found the listed domain failing DNS resolution."),("Public phone", "Phone-first CTA uses public listing details."),("Fast-lube feel", "Bay-status design language differs from the other auto pages.")]),
]


def esc(s):
    return str(s).replace('&','&amp;').replace('<','&lt;').replace('>','&gt;').replace('"','&quot;')


def route_buttons(routes):
    out=[]
    for i,(title, copy) in enumerate(routes,1):
        active=' active' if i==1 else ''
        out.append(f"<button class='route{active}' data-title='{esc(title)}' data-copy='{esc(copy)}' data-cta='Call now'><i>{i:02d}</i><span><strong>{esc(title)}</strong><small>{esc(copy[:54])}{'…' if len(copy)>54 else ''}</small></span></button>")
    return ''.join(out)


def cards(items, cls='service'):
    return ''.join(f"<article class='{cls}'><em>{i:02d}</em><div><h3>{esc(t)}</h3><p>{esc(c)}</p></div></article>" for i,(t,c) in enumerate(items,1))


def proof_cards(items):
    return ''.join(f"<div class='proof'><b>{esc(t)}</b><small>{esc(c)}</small></div>" for t,c in items)


def html(p):
    bbox=f"{p['lon']-0.09:.4f}%2C{p['lat']-0.065:.4f}%2C{p['lon']+0.09:.4f}%2C{p['lat']+0.065:.4f}"
    return f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>{esc(p['business'])} — Premium Sample Concept by SYBEORG</title>
<meta name="description" content="Premium mobile-first SYBEORG sample concept for {esc(p['business'])} in {esc(p['market'])}.">
<meta name="theme-color" content="{p['bg']}">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='18' fill='{p['bg'].replace('#','%23')}'/%3E%3Ctext x='32' y='39' font-family='Arial' font-size='21' font-weight='900' text-anchor='middle' fill='{p['accent'].replace('#','%23')}'%3E{esc(p['initials'])}%3C/text%3E%3C/svg%3E">
<style>
:root{{--ink:{p['bg']};--ink2:#171727;--paper:#fff7ed;--bone:#fffaf0;--muted:#aeb7ca;--accent:{p['accent']};--accent2:{p['accent2']};--line:rgba(255,250,240,.16);--glass:rgba(255,250,240,.07);--shadow:0 30px 100px rgba(0,0,0,.42)}}
*{{box-sizing:border-box;margin:0;padding:0}} html{{scroll-behavior:smooth;overflow-x:hidden}} body{{min-height:100vh;background:var(--ink);color:var(--bone);font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;overflow-x:hidden;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility;padding-bottom:92px}} a{{color:inherit}} button,input,textarea{{font:inherit}} ::selection{{background:var(--accent);color:var(--ink)}}
body:before{{content:"";position:fixed;inset:0;z-index:0;pointer-events:none;background:radial-gradient(circle at 82% 4%,color-mix(in srgb,var(--accent2) 22%,transparent),transparent 32%),radial-gradient(circle at 8% 22%,color-mix(in srgb,var(--accent) 24%,transparent),transparent 34%),linear-gradient(180deg,var(--ink) 0%,#121827 54%,#05070f 100%)}} body:after{{content:"";position:fixed;inset:0;z-index:1;pointer-events:none;opacity:.24;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='160' height='160'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.85' numOctaves='2'/%3E%3CfeColorMatrix values='0 0 0 0 1 0 0 0 0 .92 0 0 0 0 .72 0 0 0 .042 0'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")}}
.loader{{position:fixed;inset:0;z-index:999;background:radial-gradient(circle at 50% 42%,color-mix(in srgb,var(--accent) 16%,transparent),transparent 34%),var(--ink);display:grid;place-items:center;animation:loaderOut .7s ease 1.35s forwards}}.loader-card{{display:grid;place-items:center;gap:18px;transform:translateY(8px);animation:loaderIn .8s cubic-bezier(.2,.8,.2,1) forwards}}.loader-logo{{width:96px;height:96px;border-radius:30px;background:var(--bone);color:var(--ink);display:grid;place-items:center;font-weight:950;font-size:25px;letter-spacing:-.06em;box-shadow:0 28px 70px rgba(0,0,0,.38);position:relative;overflow:hidden}}.loader-logo:after{{content:"";position:absolute;inset:-40%;background:linear-gradient(115deg,transparent 30%,rgba(255,255,255,.9),transparent 58%);transform:translateX(-80%);animation:sheen 1.25s ease .35s forwards}}.loader small{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--accent);letter-spacing:.24em;text-transform:uppercase;font-size:10px}}@keyframes loaderIn{{to{{transform:none}}}}@keyframes loaderOut{{to{{opacity:0;visibility:hidden}}}}@keyframes sheen{{to{{transform:translateX(85%)}}}}
.page{{position:relative;z-index:2}}.sample{{position:relative;z-index:3;background:#02040b;color:color-mix(in srgb,var(--accent) 82%,white);text-align:center;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:9px;letter-spacing:.18em;text-transform:uppercase;padding:9px 14px;border-bottom:1px solid var(--line)}}
.nav{{position:sticky;top:0;z-index:50;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 14px;background:rgba(7,9,20,.72);backdrop-filter:blur(20px) saturate(1.4);border-bottom:1px solid var(--line)}}.brand{{display:flex;align-items:center;gap:10px;min-width:0}}.logo{{width:44px;height:44px;border-radius:15px;background:var(--bone);color:var(--ink);display:grid;place-items:center;font-weight:950;letter-spacing:-.08em;box-shadow:0 12px 34px rgba(0,0,0,.32)}}.brand b{{display:block;font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}}.brand span{{display:block;color:var(--muted);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:8px;letter-spacing:.15em;text-transform:uppercase;margin-top:1px}}.mini-call{{display:inline-flex;align-items:center;justify-content:center;text-decoration:none;background:var(--accent);color:#05070f;border-radius:999px;padding:10px 12px;font-size:12px;font-weight:950;white-space:nowrap}}
.hero{{min-height:calc(100svh - 100px);display:flex;flex-direction:column;justify-content:space-between;padding:30px 18px 20px;position:relative;overflow:hidden}}.hero:before{{content:"";position:absolute;right:-150px;top:42px;width:360px;height:360px;border:1px solid color-mix(in srgb,var(--accent) 42%,transparent);border-radius:50%;box-shadow:inset 0 0 80px color-mix(in srgb,var(--accent2) 12%,transparent)}}.hero-sigil{{position:absolute;right:-48px;bottom:150px;width:210px;height:210px;opacity:.42;animation:float 8s ease-in-out infinite}}@keyframes float{{50%{{transform:translateY(-14px) rotate(2deg)}}}}.chapter{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--accent);font-size:10px;letter-spacing:.24em;text-transform:uppercase;display:flex;align-items:center;gap:12px}}.chapter:before{{content:"";width:34px;height:1px;background:var(--accent)}}h1{{font-size:clamp(48px,15vw,92px);line-height:.87;font-weight:850;letter-spacing:-.075em;margin-top:22px;max-width:790px}}.accent-word{{font-family:Georgia,serif;font-style:italic;color:var(--accent);font-weight:500;letter-spacing:-.055em}}.lede{{margin-top:20px;color:#d7d2c4;font-family:Georgia,serif;font-size:22px;line-height:1.3;max-width:650px}}.actions{{display:grid;gap:10px;margin-top:24px}}.primary,.secondary{{min-height:56px;border-radius:18px;display:flex;align-items:center;justify-content:center;text-decoration:none;font-weight:950}}.primary{{background:var(--bone);color:var(--ink);box-shadow:0 18px 42px rgba(255,250,240,.16)}}.secondary{{background:rgba(255,255,255,.04);border:1px solid var(--line);color:var(--bone)}}.ticker{{margin:30px -18px 0;padding:12px 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line);overflow:hidden;background:rgba(255,250,240,.035)}}.ticker-track{{display:flex;width:max-content;gap:26px;animation:marquee 30s linear infinite}}.ticker-track span{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:10px;color:var(--accent);letter-spacing:.18em;text-transform:uppercase}}@keyframes marquee{{to{{transform:translateX(-50%)}}}}
.section{{padding:60px 18px;border-top:1px solid rgba(255,250,240,.08)}}.wrap{{max-width:1120px;margin:0 auto}}.label{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--accent);font-size:10px;letter-spacing:.24em;text-transform:uppercase;margin-bottom:18px}}.section h2{{font-size:clamp(42px,9vw,70px);line-height:.93;font-weight:760;letter-spacing:-.055em}}.section p{{color:#c9c3b8;font-size:16px;line-height:1.72;margin-top:14px}}.panel{{margin-top:22px;border:1px solid var(--line);border-radius:30px;background:linear-gradient(180deg,rgba(255,250,240,.09),rgba(255,250,240,.035));box-shadow:var(--shadow);overflow:hidden}}.panel-head{{padding:20px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:14px}}.panel-head b{{font-family:Georgia,serif;font-size:28px;font-weight:600;line-height:1}}.panel-head small{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:9px;color:var(--accent2);letter-spacing:.16em;text-transform:uppercase}}.routes{{padding:10px;display:grid;gap:8px}}.route{{border:1px solid rgba(255,250,240,.13);background:rgba(0,0,0,.18);border-radius:19px;padding:14px;text-align:left;display:grid;grid-template-columns:38px 1fr;gap:12px;align-items:center;color:var(--bone);cursor:pointer}}.route.active{{background:color-mix(in srgb,var(--accent) 15%,transparent);border-color:color-mix(in srgb,var(--accent) 55%,transparent)}}.route i{{width:38px;height:38px;border-radius:14px;display:grid;place-items:center;background:rgba(120,212,255,.12);color:var(--accent2);font-style:normal;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px}}.route strong{{display:block;font-size:15px}}.route small{{display:block;margin-top:3px;color:var(--muted);font-size:12px}}.result{{margin:10px;border-radius:22px;background:var(--bone);color:var(--ink);padding:20px}}.result .eyebrow{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:9px;letter-spacing:.18em;text-transform:uppercase;color:color-mix(in srgb,var(--accent) 70%,#593b00)}}.result h3{{font-size:30px;letter-spacing:-.04em;margin-top:8px}}.result p{{color:#374151;margin-top:8px}}.result a{{display:inline-flex;margin-top:14px;color:var(--ink);font-weight:950}}
.service-grid{{display:grid;gap:12px;margin-top:22px}}.service{{border-top:1px solid var(--line);padding:18px 0;display:grid;grid-template-columns:42px 1fr;gap:14px}}.service em{{font-style:normal;color:var(--accent);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px}}.service h3{{font-size:28px;line-height:1;font-weight:760;letter-spacing:-.035em}}.service p{{font-size:14px;margin-top:6px}}.map{{height:320px;margin-top:22px;border-radius:26px;border:1px solid var(--line);position:relative;overflow:hidden;background:#0d1127;box-shadow:0 22px 70px rgba(0,0,0,.26)}}.map iframe{{position:absolute;inset:0;width:100%;height:100%;border:0;filter:saturate(.82) contrast(.92)}}.map-meta{{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}}.map-meta span,.map-link{{border:1px solid var(--line);border-radius:999px;padding:8px 10px;background:rgba(255,250,240,.055);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:9px;letter-spacing:.12em;text-transform:uppercase;text-decoration:none}}.map-link{{color:var(--accent)}}.contact-card{{margin-top:22px;border:1px solid var(--line);border-radius:30px;padding:22px;background:rgba(255,250,240,.06);box-shadow:var(--shadow)}}.contact-grid{{display:grid;gap:12px;margin-top:18px}}.field{{width:100%;border:1px solid var(--line);background:rgba(0,0,0,.18);border-radius:16px;padding:15px;color:var(--bone);outline:none}}textarea.field{{min-height:110px;resize:vertical}}.field::placeholder{{color:#8d95a7}}.proof-grid{{display:grid;gap:12px;margin-top:22px}}.proof{{border:1px solid var(--line);border-radius:22px;padding:18px;background:rgba(255,250,240,.045)}}.proof b{{font-size:24px;letter-spacing:-.035em}}.proof small{{display:block;color:var(--muted);margin-top:6px;line-height:1.45}}.final{{margin:58px 18px 28px;border:1px solid color-mix(in srgb,var(--accent) 45%,transparent);border-radius:34px;padding:28px 22px;background:linear-gradient(135deg,color-mix(in srgb,var(--accent) 16%,transparent),rgba(120,212,255,.08));box-shadow:var(--shadow)}}.final p{{color:#c9c3b8;line-height:1.65;margin-top:12px}}footer{{position:relative;z-index:2;color:#7f8795;text-align:center;padding:24px 18px 110px;font-size:12px;line-height:1.6}}.bottom-call{{position:fixed;left:10px;right:10px;bottom:10px;z-index:80;display:grid;grid-template-columns:1fr auto;gap:8px;padding:8px;border:1px solid var(--line);border-radius:23px;background:rgba(7,9,20,.78);backdrop-filter:blur(18px)}}.bottom-call a{{min-height:50px;border-radius:17px;display:flex;align-items:center;justify-content:center;text-decoration:none;font-weight:950}}.bottom-call .call{{background:var(--accent);color:#05070f}}.bottom-call .mini{{border:1px solid var(--line);padding:0 16px;color:var(--bone)}}
@media(min-width:780px){{body{{padding-bottom:0}}.nav{{padding:18px 48px}}.logo{{width:58px;height:58px;border-radius:19px;font-size:20px}}.brand b{{font-size:18px}}.brand span{{font-size:10px}}.hero{{min-height:760px;padding:92px 56px 36px}}.hero-inner{{max-width:1240px;margin:0 auto;width:100%;display:grid;grid-template-columns:1fr 430px;gap:56px;align-items:end}}.actions{{grid-template-columns:auto auto;justify-content:start}}.section{{padding:88px 56px}}.two{{display:grid;grid-template-columns:.84fr 1.16fr;gap:42px;align-items:start}}.service-grid{{grid-template-columns:1fr 1fr;gap:0 28px}}.proof-grid{{grid-template-columns:repeat(3,1fr)}}.contact-grid{{grid-template-columns:1fr 1fr}}.contact-grid .wide{{grid-column:1/-1}}.final{{max-width:1120px;margin:88px auto 52px;padding:46px;display:grid;grid-template-columns:1fr auto;gap:40px;align-items:center}}.final .primary{{margin-top:0;min-width:220px}}.bottom-call{{display:none}}.hero-sigil{{width:320px;height:320px;right:6vw;bottom:80px}}}}
@media(prefers-reduced-motion:reduce){{*,*:before,*:after{{animation:none!important;transition:none!important;scroll-behavior:auto!important}}.loader{{display:none}}}}
</style>
</head>
<body>
<div class="loader" aria-label="Loading {esc(p['business'])} concept"><div class="loader-card"><div class="loader-logo">{esc(p['initials'])}</div><small>{esc(p['business'])}</small></div></div>
<div class="sample">SYBEORG sample concept — not the official website of {esc(p['business'])}</div>
<div class="page">
<nav class="nav"><div class="brand"><div class="logo">{esc(p['initials'])}</div><div><b>{esc(p['business'])}</b><span>{esc(p['market'])} {esc(p['vertical'])} concept</span></div></div><a class="mini-call" href="tel:{p['tel']}">Call now</a></nav>
<header class="hero"><svg class="hero-sigil" viewBox="0 0 200 200" aria-hidden="true"><circle cx="100" cy="100" r="78" fill="none" stroke="color-mix(in srgb, var(--accent) 55%, transparent)"/><circle cx="100" cy="100" r="46" fill="none" stroke="rgba(120,212,255,.45)"/><path d="M42 132c26-68 93-70 116-30M50 72c48 2 76 32 84 78" fill="none" stroke="color-mix(in srgb, var(--accent) 72%, transparent)" stroke-width="7" stroke-linecap="round"/><path d="M72 128l56-56" stroke="rgba(120,212,255,.7)" stroke-width="2"/></svg><div class="hero-inner"><div><div class="chapter">01 · {esc(p['section'])}</div><h1>{esc(p['headline']).replace(' ', ' ', 1)} <span class="accent-word"></span></h1><p class="lede">{esc(p['lede'])}</p><div class="actions"><a class="primary" href="tel:{p['tel']}">Call {esc(p['phone'])}</a><a class="secondary" href="#contact">Contact concept</a></div></div><div class="contact-card"><div class="label">verified hook</div><p style="margin-top:0">{esc(p['issue']).capitalize()}. This page is framed as a sample first-screen fix using only public facts and room for approved proof.</p></div></div><div class="ticker"><div class="ticker-track"><span>{esc(p['vertical'])}</span><span>{esc(p['market'])}</span><span>tap-to-call</span><span>map ready</span><span>contact path</span><span>{esc(p['vertical'])}</span><span>{esc(p['market'])}</span><span>tap-to-call</span><span>map ready</span><span>contact path</span></div></div></header>
<section class="section" id="paths"><div class="wrap two"><div><div class="label">02 · interactive routing</div><h2>Make the next step feel obvious.</h2><p>This is where the page stops feeling like a flat template. The visitor taps the need, the response changes, and the call path stays close.</p></div><div class="panel"><div class="panel-head"><b>What do you need?</b><small>Tap one</small></div><div class="routes">{route_buttons(p['routes'])}</div><div class="result"><div class="eyebrow">Recommended response</div><h3 id="resultTitle">{esc(p['routes'][0][0])}</h3><p id="resultCopy">{esc(p['routes'][0][1])}</p><a id="resultCta" href="tel:{p['tel']}">Call now</a></div></div></div></section>
<section class="section"><div class="wrap two"><div><div class="label">03 · local map</div><h2>Ground the business in {esc(p['market'])}.</h2><p>A real map section gives the design local weight. Production can connect this to Google Maps, call tracking, quote forms, and service-area pages.</p></div><div><div class="map"><iframe title="{esc(p['business'])} local map" loading="lazy" referrerpolicy="no-referrer" sandbox="allow-scripts allow-same-origin allow-popups" src="https://www.openstreetmap.org/export/embed.html?bbox={bbox}&amp;layer=mapnik&amp;marker={p['lat']:.6f}%2C{p['lon']:.6f}"></iframe></div><div class="map-meta"><span>{esc(p['market'])}</span><span>Mobile-first</span><span>Local call path</span><a class="map-link" href="https://www.openstreetmap.org/?mlat={p['lat']:.6f}&amp;mlon={p['lon']:.6f}#map=13/{p['lat']:.6f}/{p['lon']:.6f}" target="_blank" rel="noopener noreferrer">Open map</a></div></div></div></section>
<section class="section"><div class="wrap"><div class="label">04 · service lanes</div><h2>Clean service structure, no clutter.</h2><div class="service-grid">{cards(p['services'])}</div></div></section>
<section class="section" id="contact"><div class="wrap two"><div><div class="label">05 · contact us</div><h2>A contact section that still sells.</h2><p>Not a dead form dropped at the bottom. The contact block repeats the phone, sets expectations, and gives a clean path for non-urgent leads.</p></div><div class="contact-card"><h3 style="font-size:30px;letter-spacing:-.04em">Contact {esc(p['business'])}</h3><p>Concept form only. Production would route to {esc(p['business'])}’s approved email, phone, or booking workflow.</p><div class="contact-grid"><input class="field" placeholder="Name"><input class="field" placeholder="Phone"><textarea class="field wide" placeholder="What do you need help with?"></textarea><a class="primary wide" href="tel:{p['tel']}">Call {esc(p['phone'])}</a></div></div></div></section>
<section class="section"><div class="wrap"><div class="label">06 · credibility guardrails</div><h2>Premium does not mean fake.</h2><div class="proof-grid">{proof_cards(p['proof'])}</div></div></section>
<section class="final"><div><div class="label">ready to polish</div><h2>Built to feel custom before the first conversation.</h2><p>Logo/brand assets can be swapped in once approved. The important part is the standard: loader, motion, map, contact, local copy, and a polished page that feels built for this business.</p></div><a class="primary" href="tel:{p['tel']}">Call now</a></section>
</div><div class="bottom-call"><a class="call" href="tel:{p['tel']}">Call {esc(p['phone'])}</a><a class="mini" href="#paths">Paths</a></div><footer>Sample concept by SYBEORG. Public facts only; production version should use approved logo, photos, services, hours, reviews, and business claims.</footer>
<script>
window.addEventListener('load',()=>document.body.classList.add('loaded'));
const routes=[...document.querySelectorAll('.route')], title=document.getElementById('resultTitle'), copy=document.getElementById('resultCopy'), cta=document.getElementById('resultCta');
routes.forEach(route=>route.addEventListener('click',()=>{{routes.forEach(r=>r.classList.remove('active'));route.classList.add('active');title.textContent=route.dataset.title;copy.textContent=route.dataset.copy;cta.textContent=route.dataset.cta;}}));
</script>
</body>
</html>'''

for p in PAGES:
    d=ROOT/p['id']
    d.mkdir(exist_ok=True)
    (d/'index.html').write_text(html(p), encoding='utf-8')

# update tracker statuses
tracker=ROOT/'mockups.json'
data=json.loads(tracker.read_text(encoding='utf-8'))
ids={p['id'] for p in PAGES}
for item in data.get('currentProspects',[]):
    if item.get('id') in ids:
        item['redesignStatus']='premium_loader_map_contact_motion_ready_2026-06-21'
        item['qualityDirection']='Premium mobile-first redesign with loader, interactive routing, local map, contact section, sticky mobile CTA, and public-facts-only proof guardrails.'
        item['qualityGatePassed']=True
        item['revisionNeededBeforeOutreach']=False
        item['visualQaNotes']='Generated to SYBEORG premium standard; pending browser QA after this redesign pass.'
data['updatedBy']='Hermes / SYBEORG redesign readiness 2026-06-21'
data['lastUpdated']='2026-06-21'
tracker.write_text(json.dumps(data, indent=2), encoding='utf-8')
print('generated', len(PAGES), 'premium pages')
